name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Install Poetry
        run: pipx install poetry==1.7.1
      - name: Create Virtual Environment
        run: poetry config --local virtualenvs.in-project true
      - name: Setup Python and Poetry
        uses: ITProKyle/action-setup-python@v0.4.0
        with:
          python-version: 3.11.6
          poetry-version: 1.7.1
      - name: Run PyInstaller
        run: pyinstaller -n test-actions
      - name: Zip dist files
        run: zip -r dist/linux.zip dist/test-actions
      - name: Upload artifact
        uses: actions/upload-artifact@v3.1.3
        with:
          name: linux.zip
          path: dist/linux.zip
      - run: echo "This job's status is ${{ job.status }}."
