name: Package with PyInstaller
on:
  push:
  workflow_dispatch:
jobs:
  package:
    name: Packaging on ${{ matrix.os }}
    runs-on: ${{ matrix.runner }}
    strategy:
      fail-fast: false
      matrix:
        os: [linux, windows, macos]
        include:
          - os: linux
            runner: ubuntu-latest
            zip_name: linux
          - os: windows
            runner: windows-latest
            zip_name: windows
          #- os: macos-arm64
          #  target_arch: arm64
          #  shell: arch -arm64 bash {0}
          #  runner: macOS-latest
          #  zip_name: macos-arm64
          - os: macos
            target_arch: universal2
            runner: macOS-latest
            zip_name: macos
    defaults:
      run:
        shell: ${{ matrix.shell || 'bash' }}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          submodules: recursive
          token: ${{ secrets.PAT }}

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: 18.13.0

      - name: Get full Node.js version
        id: full-node-version
        run: echo version=$(node --version) >> $GITHUB_OUTPUT
  
      - name: Setup Node.js cache
        uses: actions/cache@v3
        with:
          path: client/node_modules
          key: node_modules-${{ matrix.os }}-${{ steps.full-node-version.outputs.version }}-${{ hashFiles('client/**/package-lock.json') }}

      - name: Compile client
        run: make
  
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Get full Python version
        id: full-python-version
        run: echo version=$(python -c "import sys; print('-'.join(str(v) for v in sys.version_info))") >> $GITHUB_OUTPUT

      - name: Install poetry
        run: curl -sSL https://install.python-poetry.org | POETRY_VERSION=1.8.2 python - -y

      - name: A little hackery for MacOS
        if: ${{ matrix.os == 'macos' }}
        run: sed -ie 's/append("universal2")/insert(0, "universal2")/' ~/Library/Application\ Support/pypoetry/venv/lib/python3.*/site-packages/poetry/core/_vendor/packaging/tags.py

      - name: Update PATH
        if: ${{ matrix.os != 'windows' }}
        run: echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Update PATH for Windows
        if: ${{ matrix.os == 'windows' }}
        run: echo "$APPDATA\Python\Scripts" >> $GITHUB_PATH

      - name: Configure poetry
        run: poetry config virtualenvs.in-project true

      - name: Setup Python cache
        uses: actions/cache@v3
        with:
          path: .venv
          key: venv-${{ matrix.os }}-${{ steps.full-python-version.outputs.version }}-${{ hashFiles('**/poetry.lock') }}

      - name: Install dependencies
        run: poetry install --with actions

      - name: Run PyInstaller
        if: ${{ matrix.runner != 'macOS-latest' }}
        run: poetry run pyinstaller -n ${{ matrix.os }}-test-actions --collect-all test_actions test_actions/_entrypoint.py --onefile

      - name: Run PyInstaller for Mac OS
        if: ${{ matrix.runner == 'macOS-latest' }}
        run: poetry run pyinstaller -n ${{ matrix.os }}-test-actions --collect-all test_actions test_actions/_entrypoint.py --onefile --target-arch ${{ matrix.target_arch }}

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.zip_name }}
          path: dist
