name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Install Poetry
        run: pipx install poetry==1.7.1
      - name: Setup Python
        uses: actions/setup-python@v4.7.1
        with:
          python-version: 3.11.6
          cache: poetry
      - name: Run PyInstaller in venv
        run: |
          python3.11 -m venv .venv
          source .venv/bin/activate
          poetry install
          pyinstaller -n test-actions test_actions/__main__.py
      - name: Zip dist files
        run: zip -r dist/linux.zip dist/test-actions
      - name: Upload artifact
        uses: actions/upload-artifact@v3.1.3
        with:
          name: linux.zip
          path: dist/linux.zip
      - run: echo "This job's status is ${{ job.status }}."
