name: Package with PyInstaller
run-name: ${{ github.actor }} is compiling ${{ github.ref_name }}
on: [push]
jobs:
  package:
    name: Packaging on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Install Poetry
        run: pipx install poetry==1.7.1
      - name: Setup Python
        uses: actions/setup-python@v4.7.1
        with:
          python-version: 3.11
          cache: poetry
      - name: Run PyInstaller in venv
        run: |
          python3.11 -m venv .venv
          source .venv/bin/activate
          poetry install --with dev
          pyinstaller -n test-actions test_actions/__main__.py
      - name: Zip dist files
        run: |
          cd dist
          zip -r linux.zip test-actions
      - name: Upload artifact
        uses: actions/upload-artifact@v3.1.3
        with:
          name: linux.zip
          path: dist/linux.zip
