name: Release

on:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      actions: read
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v5.0.0
      with:
        python-version: 3.11
    - id: get-run-id
      run: |
        python3 -m pip install requests
        python3 > $GITHUB_OUTPUT << EOF
        import requests
        r = requests.get(
          'https://api.github.com/repos/david-why/test-actions/actions/workflows/78330850/runs',
          headers={
            'Accept': 'application/vnd.github+json',
            'Authorization': 'Bearer ${{ secrets.GITHUB_TOKEN }}',
            'X-GitHub-Api-Version': '2022-11-28'
          }
        )
        print(f"run-id={r.json()['workflow_runs'][0]['id']}&commit={r.json()['workflow_runs'][0]['head_sha']}")
        EOF
    - uses: actions/download-artifact@v4.1.4
      with:
        run-id: ${{ steps.get-run-id.outputs.run-id }}
        github-token: ${{ secrets.ACTIONS_PAT }}
    - uses: ncipollo/release-action@v1
      with:
        artifacts: "windows/*,linux/*,macos-x86_64/*"
        removeArtifacts: true
        tag: nightly
        commit: ${{ steps.get-run-id.outputs.commit }}
        prerelease: true
        allowUpdates: true
        name: Nightly Release
        body: Automatic nightly release from GitHub Actions
